#!/bin/sh

#outdir=../html
outdir=../../prabh-t.github.io

cd md/
for f in *.md; do 
 fout=$outdir/${f%.*}.html
 echo Converting $f to $fout;
 pandoc $f -o $fout --template ../template/default.html --css css/markdown10.css --title-prefix=prabh-t.github.io
done
